#pragma once

#include <jni.h>

// Generated by hand to match com.rtxmc.render.NativeBridge.
// (We deliberately do NOT use javah-style names; we register manually in
// JNI_OnLoad for slightly faster lookup and so a refactor on the Java side
// fails loudly at registration time instead of silently at first call.)

extern "C" {
JNIEXPORT jint  JNICALL rtxmc_native_init(JNIEnv*, jclass, jlong hwnd, jint w, jint h);
JNIEXPORT void  JNICALL rtxmc_native_resize(JNIEnv*, jclass, jint w, jint h);
JNIEXPORT void  JNICALL rtxmc_native_uploadChunk(JNIEnv*, jclass,
                                                 jint cx, jint cy, jint cz, jint layer,
                                                 jobject verts);
JNIEXPORT void  JNICALL rtxmc_native_removeChunk(JNIEnv*, jclass, jint cx, jint cy, jint cz);
JNIEXPORT void  JNICALL rtxmc_native_uploadBlockAtlas(JNIEnv*, jclass,
                                                     jint w, jint h, jobject pixels);
JNIEXPORT void  JNICALL rtxmc_native_uploadEntityBatch(JNIEnv*, jclass,
                                                      jint layer_hash, jint vertex_count,
                                                      jobject verts);
JNIEXPORT void  JNICALL rtxmc_native_renderFrame(JNIEnv*, jclass, jobject params);
JNIEXPORT void  JNICALL rtxmc_native_shutdown(JNIEnv*, jclass);

JNIEXPORT void  JNICALL rtxmc_dlss_setSr(JNIEnv*, jclass, jint preset);
JNIEXPORT void  JNICALL rtxmc_dlss_setRr(JNIEnv*, jclass, jint preset);
JNIEXPORT void  JNICALL rtxmc_dlss_setFg(JNIEnv*, jclass, jint factor);

// Phase 1.6.1b — VkBackend resource primitives. Mirror MC's GpuDevice
// creation surface; return opaque uint64_t handles that Java holds.
JNIEXPORT jlong JNICALL rtxmc_vkres_createBuffer(JNIEnv*, jclass,
                                                 jint usage, jlong size,
                                                 jobject optionalInitialData);
JNIEXPORT void  JNICALL rtxmc_vkres_destroyBuffer(JNIEnv*, jclass, jlong handle);
JNIEXPORT jobject JNICALL rtxmc_vkres_mapBuffer(JNIEnv*, jclass,
                                                jlong handle, jlong offset, jlong length);
JNIEXPORT void  JNICALL rtxmc_vkres_unmapBuffer(JNIEnv*, jclass, jlong handle);

JNIEXPORT jlong JNICALL rtxmc_vkres_createTexture(JNIEnv*, jclass,
                                                  jint usage, jint formatCode,
                                                  jint width, jint height,
                                                  jint depthOrLayers, jint mipLevels);
JNIEXPORT void  JNICALL rtxmc_vkres_destroyTexture(JNIEnv*, jclass, jlong handle);

JNIEXPORT jlong JNICALL rtxmc_vkres_createTextureView(JNIEnv*, jclass,
                                                     jlong textureHandle,
                                                     jint baseMip, jint mipLevels);
JNIEXPORT void  JNICALL rtxmc_vkres_destroyTextureView(JNIEnv*, jclass, jlong handle);

JNIEXPORT jlong JNICALL rtxmc_vkres_createSampler(JNIEnv*, jclass,
                                                  jint addrU, jint addrV,
                                                  jint minFilter, jint magFilter,
                                                  jint maxAniso);
JNIEXPORT void  JNICALL rtxmc_vkres_destroySampler(JNIEnv*, jclass, jlong handle);
}
