#pragma once

#include <jni.h>

// Generated by hand to match com.rtxmc.render.NativeBridge.
// (We deliberately do NOT use javah-style names; we register manually in
// JNI_OnLoad for slightly faster lookup and so a refactor on the Java side
// fails loudly at registration time instead of silently at first call.)

extern "C" {
JNIEXPORT jint  JNICALL rtxmc_native_init(JNIEnv*, jclass, jlong hwnd, jint w, jint h);
JNIEXPORT void  JNICALL rtxmc_native_resize(JNIEnv*, jclass, jint w, jint h);
JNIEXPORT void  JNICALL rtxmc_native_uploadChunk(JNIEnv*, jclass,
                                                 jint cx, jint cy, jint cz, jint layer,
                                                 jobject verts);
JNIEXPORT void  JNICALL rtxmc_native_removeChunk(JNIEnv*, jclass, jint cx, jint cy, jint cz);
JNIEXPORT void  JNICALL rtxmc_native_uploadBlockAtlas(JNIEnv*, jclass,
                                                     jint w, jint h, jobject pixels);
JNIEXPORT void  JNICALL rtxmc_native_renderFrame(JNIEnv*, jclass, jobject params);
JNIEXPORT void  JNICALL rtxmc_native_shutdown(JNIEnv*, jclass);

JNIEXPORT void  JNICALL rtxmc_dlss_setSr(JNIEnv*, jclass, jint preset);
JNIEXPORT void  JNICALL rtxmc_dlss_setRr(JNIEnv*, jclass, jint preset);
JNIEXPORT void  JNICALL rtxmc_dlss_setFg(JNIEnv*, jclass, jint factor);
}
